[note]
filename = "{{title}}"
template = "default.md"

[format.markdown]
hashtags = true
colon-tags = true
multiword-tags = true

[tool]
editor = "nvim"

[lsp.diagnostics]
dead-link = "none"

[group.daily]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
template = "daily.md"

[group."work/career"]

[group."work/career".note]
filename = "{{slug title}}"
template = "career.md"

[alias]
d = 'zk new daily --no-input'
c = 'nvim "$ZK_NOTEBOOK_DIR/.zk/config.toml"'
l = 'zk list --interactive $@'
m = 'zk list --interactive --match $@'
t = 'zk list --interactive --tag $@'
lt = 'zk tag list'
ca = 'zk new --title="$@" work/career'
